
version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-cqrs
    restart: always
    ports:
      - 27018:27017
    volumes:
      - ./data:/mongo_data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    expose:
      - 27018
    command: --quiet

  mongo-express:
    image: mongo-express
    container_name: mongo-express-cqrs
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongodb

  zookeeper:
    image: bitnami/zookeeper
    container_name: zookeeper-cqrs
    restart: always
    ports:
      - 2181:2181
    volumes:
      - ./data:/zookeeper_data 
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    expose:
      - 2181

  kafka:
    image: bitnami/kafka
    container_name: kafka-cqrs
    ports:
      - 9092:9092
    restart: always
    volumes:
      - ./data:/kafka_data 
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    expose:
      - 9092
    depends_on:
      - zookeeper

  mysqldb:
    image: mysql:latest
    container_name: mysqldb-cqrs
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 3306:3306
    volumes:
      - ./data:/mysql_data 

  adminer_container:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysqldb
    ports:
      - 8080:8080

networks:
  default:
    external:
      name: techbankNet
